export const mockUser = {
  id: '1',
  name: 'Alex Chen',
  username: 'alexchen',
  email: 'alex@example.com',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
  bio: 'Senior Full-Stack Engineer @ TechCorp. Passionate about distributed systems, Rust, and TypeScript.',
  location: 'San Francisco, CA',
  website: 'https://alexchen.dev',
  github: 'alexchen',
  reputation: 4820,
  joinedAt: '2023-01-15',
  role: 'developer',
  skills: ['TypeScript', 'Rust', 'React', 'Node.js', 'PostgreSQL', 'Kubernetes', 'GraphQL'],
  badges: ['Top Contributor', 'Code Reviewer', 'Mentor', 'Early Adopter'],
  stats: {
    questions: 47,
    answers: 183,
    reviews: 92,
    upvotes: 2841,
  },
};

export const mockQuestions = [
  {
    id: '1',
    title: 'How to efficiently handle concurrent database transactions in PostgreSQL with TypeScript?',
    body: 'I am working on a high-traffic e-commerce application and facing issues with concurrent database transactions. Getting serialization errors and deadlocks...',
    tags: ['typescript', 'postgresql', 'concurrency', 'transactions'],
    author: { name: 'Sarah Kim', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&crop=face', reputation: 3200 },
    votes: 42, answers: 7, views: 1840, accepted: true, createdAt: '2024-01-20T10:30:00Z',
  },
  {
    id: '2',
    title: 'Memory leak in React useEffect cleanup with WebSocket connections',
    body: 'Getting memory leak warnings in React when using WebSocket connections inside useEffect. Chrome DevTools shows memory growing continuously...',
    tags: ['react', 'websocket', 'hooks', 'memory-leak'],
    author: { name: 'Marcus Lee', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=40&h=40&fit=crop&crop=face', reputation: 1750 },
    votes: 31, answers: 5, views: 920, accepted: false, createdAt: '2024-01-19T14:22:00Z',
  },
  {
    id: '3',
    title: 'Best practices for implementing CQRS pattern in microservices architecture',
    body: 'Trying to understand the proper way to implement CQRS with event sourcing in a microservices setup. Should I use separate databases for read and write models?',
    tags: ['microservices', 'cqrs', 'architecture', 'event-sourcing'],
    author: { name: 'Diana Patel', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&crop=face', reputation: 5100 },
    votes: 68, answers: 12, views: 3200, accepted: true, createdAt: '2024-01-18T09:15:00Z',
  },
  {
    id: '4',
    title: 'How to implement proper error handling in Rust async functions?',
    body: 'Working on a Rust backend and struggling with proper error propagation in async contexts. What is the best pattern?',
    tags: ['rust', 'async', 'error-handling'],
    author: { name: 'James Wilson', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face', reputation: 2850 },
    votes: 54, answers: 9, views: 2100, accepted: true, createdAt: '2024-01-17T11:45:00Z',
  },
  {
    id: '5',
    title: 'Optimal caching strategy for GraphQL queries in Apollo Client',
    body: 'Need to understand how to properly configure Apollo Client cache for complex nested queries without stale data issues...',
    tags: ['graphql', 'apollo', 'caching', 'performance'],
    author: { name: 'Emily Rodriguez', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&crop=face', reputation: 1920 },
    votes: 28, answers: 4, views: 650, accepted: false, createdAt: '2024-01-16T16:20:00Z',
  },
  {
    id: '6',
    title: 'Docker multi-stage build best practices for Node.js production',
    body: 'Building Docker images for Node.js microservices. Want to optimize for minimal image size and security...',
    tags: ['docker', 'nodejs', 'devops', 'containerization'],
    author: { name: 'Kevin Chen', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=40&h=40&fit=crop&crop=face', reputation: 3450 },
    votes: 76, answers: 14, views: 4200, accepted: true, createdAt: '2024-01-15T13:10:00Z',
  },
  {
    id: '7',
    title: 'How to debug SQL N+1 problems in a large application?',
    body: 'My application is making too many database queries. How can I identify and fix N+1 problems efficiently?',
    tags: ['sql', 'performance', 'database', 'debugging'],
    author: { name: 'Lisa Park', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&crop=face', reputation: 2650 },
    votes: 45, answers: 8, views: 1500, accepted: true, createdAt: '2024-01-14T09:30:00Z',
  },
  {
    id: '8',
    title: 'Implementing OAuth2 with Refresh Tokens in a SPA',
    body: 'Building a single-page application with OAuth2 authentication. What is the safest way to handle refresh tokens?',
    tags: ['oauth2', 'authentication', 'security', 'spa'],
    author: { name: 'Robert Taylor', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face', reputation: 4100 },
    votes: 92, answers: 16, views: 5800, accepted: true, createdAt: '2024-01-13T14:55:00Z',
  },
];

export const mockBlogs = [
  {
    id: '1',
    title: 'Building High-Performance APIs with Rust and Actix-Web',
    excerpt: 'Dive deep into creating blazing-fast REST APIs using Rust\'s Actix-Web framework, exploring async patterns, error handling, and deployment strategies.',
    author: { name: 'Alex Chen', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face' },
    tags: ['rust', 'api', 'performance', 'actix'],
    readTime: 12, views: 8420, likes: 284, createdAt: '2024-01-22T08:00:00Z',
    image: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=600&h=300&fit=crop',
  },
  {
    id: '2',
    title: 'TypeScript 5.0 Generic Patterns You Should Know',
    excerpt: 'Explore advanced TypeScript generics including conditional types, infer keyword, template literal types, and how to leverage them in real-world scenarios.',
    author: { name: 'Sarah Kim', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&crop=face' },
    tags: ['typescript', 'generics', 'patterns'],
    readTime: 8, views: 12300, likes: 445, createdAt: '2024-01-20T12:00:00Z',
    image: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=600&h=300&fit=crop',
  },
  {
    id: '3',
    title: 'PostgreSQL Query Optimization: From Slow to Blazing Fast',
    excerpt: 'Learn how to analyze slow queries, understand query plans, create proper indexes, and optimize complex SQL queries for production workloads.',
    author: { name: 'Marcus Lee', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=40&h=40&fit=crop&crop=face' },
    tags: ['postgresql', 'optimization', 'database', 'sql'],
    readTime: 15, views: 6750, likes: 312, createdAt: '2024-01-18T10:30:00Z',
    image: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&h=300&fit=crop',
  },
  {
    id: '4',
    title: 'Kubernetes Deployment Patterns for Node.js Applications',
    excerpt: 'A comprehensive guide to deploying Node.js microservices on Kubernetes, covering health checks, autoscaling, rolling updates, and observability.',
    author: { name: 'Diana Patel', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&crop=face' },
    tags: ['kubernetes', 'nodejs', 'devops', 'deployment'],
    readTime: 18, views: 9100, likes: 521, createdAt: '2024-01-15T09:00:00Z',
    image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=600&h=300&fit=crop',
  },
  {
    id: '5',
    title: 'React Performance Optimization Techniques',
    excerpt: 'Master React performance with code splitting, lazy loading, memoization, and profiling. Real-world examples and benchmarks included.',
    author: { name: 'James Wilson', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face' },
    tags: ['react', 'performance', 'optimization', 'frontend'],
    readTime: 10, views: 15600, likes: 612, createdAt: '2024-01-12T11:30:00Z',
    image: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=600&h=300&fit=crop',
  },
  {
    id: '6',
    title: 'GraphQL Best Practices for Production Systems',
    excerpt: 'Learn how to design scalable GraphQL APIs with proper error handling, pagination, subscriptions, and caching strategies.',
    author: { name: 'Emily Rodriguez', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&crop=face' },
    tags: ['graphql', 'api', 'best-practices', 'architecture'],
    readTime: 14, views: 7820, likes: 398, createdAt: '2024-01-10T14:20:00Z',
    image: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=600&h=300&fit=crop',
  },
  {
    id: '7',
    title: 'Docker and Kubernetes Security Best Practices',
    excerpt: 'Comprehensive guide to securing containerized applications with image scanning, RBAC, network policies, and secret management.',
    author: { name: 'Kevin Chen', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=40&h=40&fit=crop&crop=face' },
    tags: ['docker', 'kubernetes', 'security', 'devops'],
    readTime: 16, views: 11200, likes: 467, createdAt: '2024-01-08T09:45:00Z',
    image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=600&h=300&fit=crop',
  },
  {
    id: '8',
    title: 'Testing Microservices: Strategies and Tools',
    excerpt: 'Explore unit, integration, and end-to-end testing strategies for microservices with Jest, Vitest, and Cypress.',
    author: { name: 'Lisa Park', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&crop=face' },
    tags: ['testing', 'microservices', 'jest', 'ci-cd'],
    readTime: 13, views: 8950, likes: 356, createdAt: '2024-01-05T16:00:00Z',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&h=300&fit=crop',
  },
];

export const mockTestimonials = [
  {
    id: '1',
    name: 'Jordan Rivera',
    role: 'Senior Backend Engineer',
    company: 'Stripe',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face',
    content: 'StackTruth completely changed how I approach technical problems. The code validation engine caught a critical security flaw in my authentication module that I had missed.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Priya Nair',
    role: 'Full-Stack Developer',
    company: 'Vercel',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=80&h=80&fit=crop&crop=face',
    content: 'The quality of answers here is exceptional. Unlike other platforms, reviewers actually understand the full context of your code and architecture, not just the syntax.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Thomas Walsh',
    role: 'Engineering Manager',
    company: 'Linear',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=80&h=80&fit=crop&crop=face',
    content: 'I use StackTruth with my entire team. The collaborative workspaces and code review features have sped up our PR review process by 40%. It is a game changer.',
    rating: 5,
  },
  {
    id: '4',
    name: 'Yuki Tanaka',
    role: 'DevOps Engineer',
    company: 'Notion',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop&crop=face',
    content: 'The AI assistant is incredibly context-aware. It understands my tech stack and gives recommendations that actually fit my architecture, not generic suggestions.',
    rating: 5,
  },
];

export const pricingPlans = [
  {
    id: 'free',
    name: 'Free',
    price: { monthly: 0, yearly: 0 },
    description: 'Perfect for individual developers getting started',
    features: [
      '50 questions/month',
      'Community Q&A access',
      'Basic code snippet support',
      'Public knowledge base access',
      '5 code reviews/month',
      'Community reputation system',
    ],
    cta: 'Get Started Free',
    highlighted: false,
    badge: null,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: { monthly: 19, yearly: 15 },
    description: 'For serious developers who want to grow faster',
    features: [
      'Unlimited questions & answers',
      'AI code review engine',
      'Advanced syntax highlighting',
      'Private workspaces (3)',
      'Unlimited code reviews',
      'Priority AI assistant',
      'Badge & reputation boost',
      'API access (1000 req/day)',
    ],
    cta: 'Start Pro Trial',
    highlighted: true,
    badge: 'Most Popular',
  },
  {
    id: 'team',
    name: 'Team',
    price: { monthly: 49, yearly: 39 },
    description: 'For engineering teams that collaborate daily',
    features: [
      'Everything in Pro',
      'Unlimited team workspaces',
      'Team analytics dashboard',
      'Shared code review queue',
      'Live coding sessions',
      'Interview mode',
      'SSO & access controls',
      'Priority support',
      'API access (10k req/day)',
    ],
    cta: 'Start Team Trial',
    highlighted: false,
    badge: 'For Teams',
  },
];

export const faqData = [
  {
    question: 'How does StackTruth differ from Stack Overflow?',
    answer: 'StackTruth goes beyond Q&A by providing automated AI code review, peer review workflows, team collaboration workspaces, live coding sessions, and a dedicated knowledge base. We are built for modern engineering teams who need more than just a forum.',
  },
  {
    question: 'Is my code and data kept private?',
    answer: 'Absolutely. Private workspace content, code submissions for review, and any content you mark as private is encrypted and never shared. Public questions and answers are searchable by the community, just like you intend.',
  },
  {
    question: 'How does the AI code review engine work?',
    answer: 'Our AI engine analyzes your code for security vulnerabilities, performance bottlenecks, code smells, best practice violations, and logic errors. It provides detailed line-by-line annotations with specific suggestions, much like a senior engineer reviewing your PR.',
  },
  {
    question: 'Can I use StackTruth for technical interviews?',
    answer: 'Yes! The Live Coding module supports real-time collaborative coding with an execution sandbox. Candidates and interviewers can code together, run code, and leave comments in real-time — making remote technical interviews smooth and fair.',
  },
  {
    question: 'What languages and frameworks are supported?',
    answer: 'StackTruth supports 40+ programming languages including TypeScript, JavaScript, Python, Rust, Go, Java, C++, Ruby, and more. Syntax highlighting, code validation, and AI suggestions are tailored per language.',
  },
  {
    question: 'Do you offer discounts for open-source projects or students?',
    answer: 'Yes! We offer free Pro plans for verified open-source maintainers and 70% discounts for students with a valid .edu email. Contact us at education@stacktruth.dev for verification.',
  },
  {
    question: 'How does the reputation system work?',
    answer: 'You earn reputation points through upvotes on your answers and questions, accepted answers (+15 pts), peer code reviews (+5 pts), and badges for consistent quality contributions. Reputation unlocks privileges like voting, editing, and mentoring roles.',
  },
  {
    question: 'Can I export my data?',
    answer: 'Yes. All plans include full data portability. You can export your profile, questions, answers, code snippets, and analytics in JSON or CSV format at any time from your settings.',
  },
];

// Job listings data
export const mockJobs = [
  {
    id: '1',
    title: 'Senior Backend Engineer - Go/Rust',
    company: 'Stripe',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salary: '$250K - $350K',
    logo: 'https://images.unsplash.com/photo-1549428260-3157daeb8c56?w=100&h=100&fit=crop',
    tags: ['go', 'rust', 'backend', 'distributed-systems'],
    description: 'Join Stripe\'s payments team to build the next generation of payment processing infrastructure.',
    applications: 127,
    createdAt: '2024-01-20',
  },
  {
    id: '2',
    title: 'Frontend Engineer - React/TypeScript',
    company: 'Vercel',
    location: 'Remote',
    type: 'Full-time',
    salary: '$180K - $250K',
    logo: 'https://images.unsplash.com/photo-1549428260-3157daeb8c56?w=100&h=100&fit=crop',
    tags: ['react', 'typescript', 'nextjs', 'frontend'],
    description: 'Help developers build faster with Next.js and modern tooling.',
    applications: 89,
    createdAt: '2024-01-19',
  },
  {
    id: '3',
    title: 'DevOps Engineer - Kubernetes',
    company: 'Google Cloud',
    location: 'Mountain View, CA',
    type: 'Full-time',
    salary: '$200K - $300K',
    logo: 'https://images.unsplash.com/photo-1549428260-3157daeb8c56?w=100&h=100&fit=crop',
    tags: ['kubernetes', 'devops', 'gcp', 'infrastructure'],
    description: 'Build and maintain infrastructure for millions of developers.',
    applications: 156,
    createdAt: '2024-01-18',
  },
  {
    id: '4',
    title: 'Full-Stack Engineer - Python/React',
    company: 'Notion',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salary: '$220K - $300K',
    logo: 'https://images.unsplash.com/photo-1549428260-3157daeb8c56?w=100&h=100&fit=crop',
    tags: ['python', 'react', 'fullstack', 'databases'],
    description: 'Work on products used by millions of teams worldwide.',
    applications: 203,
    createdAt: '2024-01-17',
  },
  {
    id: '5',
    title: 'Database Engineer - PostgreSQL',
    company: 'Amazon RDS',
    location: 'Seattle, WA',
    type: 'Full-time',
    salary: '$240K - $320K',
    logo: 'https://images.unsplash.com/photo-1549428260-3157daeb8c56?w=100&h=100&fit=crop',
    tags: ['postgresql', 'databases', 'aws', 'performance'],
    description: 'Optimize and scale database systems for cloud infrastructure.',
    applications: 72,
    createdAt: '2024-01-16',
  },
  {
    id: '6',
    title: 'Mobile Engineer - React Native',
    company: 'Microsoft',
    location: 'Seattle, WA',
    type: 'Full-time',
    salary: '$200K - $280K',
    logo: 'https://images.unsplash.com/photo-1549428260-3157daeb8c56?w=100&h=100&fit=crop',
    tags: ['react-native', 'mobile', 'typescript'],
    description: 'Build cross-platform mobile applications for millions of users.',
    applications: 94,
    createdAt: '2024-01-15',
  },
];

// Leaderboard data
export const mockLeaderboard = [
  { rank: 1, name: 'Sarah Kim', reputation: 12850, badges: 8, answers: 342, avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&crop=face' },
  { rank: 2, name: 'Marcus Lee', reputation: 11200, badges: 7, answers: 298, avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=40&h=40&fit=crop&crop=face' },
  { rank: 3, name: 'Diana Patel', reputation: 10950, badges: 9, answers: 267, avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&crop=face' },
  { rank: 4, name: 'Alex Chen', reputation: 10100, badges: 6, answers: 289, avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face' },
  { rank: 5, name: 'James Wilson', reputation: 9850, badges: 7, answers: 245, avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face' },
  { rank: 6, name: 'Emily Rodriguez', reputation: 8920, badges: 5, answers: 198, avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&crop=face' },
  { rank: 7, name: 'Kevin Chen', reputation: 8350, badges: 6, answers: 172, avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=40&h=40&fit=crop&crop=face' },
  { rank: 8, name: 'Lisa Park', reputation: 7620, badges: 4, answers: 156, avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&crop=face' },
  { rank: 9, name: 'Robert Taylor', reputation: 7340, badges: 5, answers: 143, avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face' },
  { rank: 10, name: 'Priya Nair', reputation: 6890, badges: 4, answers: 128, avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&crop=face' },
];

// Code snippets for knowledge base
export const mockSnippets = [
  {
    id: '1',
    title: 'PostgreSQL Connection Pool Manager',
    language: 'typescript',
    category: 'Database',
    author: 'Sarah Kim',
    code: `import pg from 'pg';\n\nconst pool = new pg.Pool({\n  host: 'localhost',\n  port: 5432,\n  database: 'mydb',\n  user: 'user',\n  password: 'password',\n  max: 20,\n});\n\nexport default pool;`,
    views: 2840,
    likes: 156,
    tags: ['postgresql', 'connection-pooling'],
  },
  {
    id: '2',
    title: 'React Custom Hook - useAsync',
    language: 'typescript',
    category: 'Frontend',
    author: 'Marcus Lee',
    code: `import { useState, useEffect } from 'react';\n\nfunction useAsync<T>(fn: () => Promise<T>) {\n  const [data, setData] = useState<T | null>(null);\n  const [loading, setLoading] = useState(true);\n  const [error, setError] = useState<Error | null>(null);\n\n  useEffect(() => {\n    fn().then(setData).catch(setError).finally(() => setLoading(false));\n  }, [fn]);\n\n  return { data, loading, error };\n}`,
    views: 5620,
    likes: 342,
    tags: ['react', 'hooks', 'async'],
  },
  {
    id: '3',
    title: 'Rust Error Handling Pattern',
    language: 'rust',
    category: 'Backend',
    author: 'Diana Patel',
    code: `use thiserror::Error;\n\n#[derive(Error, Debug)]\npub enum ApiError {\n  #[error("Not found: {0}")]\n  NotFound(String),\n  #[error("Unauthorized")]\n  Unauthorized,\n  #[error(transparent)]\n  Other(#[from] anyhow::Error),\n}`,
    views: 1920,
    likes: 89,
    tags: ['rust', 'error-handling'],
  },
  {
    id: '4',
    title: 'GraphQL Schema Best Practices',
    language: 'graphql',
    category: 'API',
    author: 'James Wilson',
    code: `type User {\n  id: ID!\n  email: String!\n  name: String!\n  posts(first: Int, after: String): PostConnection!\n  createdAt: DateTime!\n}\n\ntype PostConnection {\n  edges: [PostEdge!]!\n  pageInfo: PageInfo!\n}`,
    views: 3450,
    likes: 198,
    tags: ['graphql', 'api-design'],
  },
  {
    id: '5',
    title: 'Docker Multi-stage Build',
    language: 'dockerfile',
    category: 'DevOps',
    author: 'Kevin Chen',
    code: `FROM node:18-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\n\nFROM node:18-alpine\nWORKDIR /app\nCOPY --from=builder /app/dist ./dist\nCOPY package*.json ./\nRUN npm ci --only=production\nCMD ["node", "dist/index.js"]`,
    views: 4120,
    likes: 267,
    tags: ['docker', 'nodejs', 'optimization'],
  },
];

// Tutorial content
export const mockTutorials = [
  {
    id: '1',
    title: 'Building Your First REST API with Node.js',
    description: 'Learn to create a complete REST API using Express, TypeScript, and PostgreSQL.',
    difficulty: 'Beginner',
    duration: '45 minutes',
    author: 'Alex Chen',
    topics: ['nodejs', 'express', 'rest-api', 'typescript'],
    students: 3420,
    rating: 4.8,
    sections: 8,
  },
  {
    id: '2',
    title: 'React Hooks Masterclass',
    description: 'Deep dive into React hooks with practical examples and patterns.',
    difficulty: 'Intermediate',
    duration: '2.5 hours',
    author: 'Sarah Kim',
    topics: ['react', 'hooks', 'state-management'],
    students: 5890,
    rating: 4.9,
    sections: 12,
  },
  {
    id: '3',
    title: 'Microservices Architecture Patterns',
    description: 'Understand and implement microservices patterns in production.',
    difficulty: 'Advanced',
    duration: '4 hours',
    author: 'Marcus Lee',
    topics: ['microservices', 'architecture', 'devops'],
    students: 1240,
    rating: 4.7,
    sections: 15,
  },
  {
    id: '4',
    title: 'TypeScript for Beginners',
    description: 'Master TypeScript from basics to advanced types.',
    difficulty: 'Beginner',
    duration: '2 hours',
    author: 'Diana Patel',
    topics: ['typescript', 'types', 'oop'],
    students: 8920,
    rating: 4.8,
    sections: 10,
  },
];

// Notifications
export const mockNotifications = [
  { id: '1', type: 'answer', message: 'Sarah Kim answered your question about PostgreSQL', time: '5 minutes ago', read: false },
  { id: '2', type: 'upvote', message: 'Your answer received 12 upvotes', time: '1 hour ago', read: false },
  { id: '3', type: 'mention', message: 'Marcus Lee mentioned you in a discussion', time: '2 hours ago', read: false },
  { id: '4', type: 'review', message: 'Your code review is complete', time: '3 hours ago', read: true },
  { id: '5', type: 'badge', message: 'You earned the "Helpful Mentor" badge', time: '1 day ago', read: true },
  { id: '6', type: 'team', message: 'You were added to the Backend Platform team', time: '2 days ago', read: true },
];

// Answers for questions
export const mockAnswers = [
  {
    id: 'a1',
    questionId: '1',
    author: { name: 'Diana Patel', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&crop=face', reputation: 5100 },
    content: 'The key to handling concurrent transactions is using appropriate isolation levels and retrying logic. Here\'s a production pattern I use:\n\n```typescript\nconst executeWithRetry = async (fn, maxRetries = 3) => {\n  for (let i = 0; i < maxRetries; i++) {\n    try {\n      return await fn();\n    } catch (e) {\n      if (e.code === \'40P01\' && i < maxRetries - 1) {\n        await new Promise(r => setTimeout(r, 100 * (i + 1)));\n        continue;\n      }\n      throw e;\n    }\n  }\n};\n```\n\nAlso consider using SERIALIZABLE isolation level for critical transactions.',
    votes: 28,
    accepted: true,
    createdAt: '2024-01-20T12:30:00Z',
  },
  {
    id: 'a2',
    questionId: '1',
    author: { name: 'Robert Taylor', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face', reputation: 4100 },
    content: 'Use connection pooling with proper timeout configurations. Also, always use transactions wisely - don\'t hold locks longer than necessary.',
    votes: 14,
    accepted: false,
    createdAt: '2024-01-20T14:00:00Z',
  },
  {
    id: 'a3',
    questionId: '2',
    author: { name: 'James Wilson', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face', reputation: 2850 },
    content: 'Make sure you\'re properly cleaning up WebSocket event listeners in your useEffect cleanup function. Return a cleanup function that removes all listeners.',
    votes: 18,
    accepted: false,
    createdAt: '2024-01-19T16:30:00Z',
  },
];

// User search results
export const mockSearchUsers = [
  { id: '1', name: 'Sarah Kim', username: 'sarahkim', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&crop=face', reputation: 3200, skills: ['TypeScript', 'React', 'PostgreSQL'] },
  { id: '2', name: 'Marcus Lee', username: 'marcuslee', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=40&h=40&fit=crop&crop=face', reputation: 1750, skills: ['Rust', 'Go', 'System Design'] },
  { id: '3', name: 'Diana Patel', username: 'dianapatel', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&crop=face', reputation: 5100, skills: ['Architecture', 'DevOps', 'Kubernetes'] },
  { id: '4', name: 'James Wilson', username: 'jameswilson', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face', reputation: 2850, skills: ['Python', 'ML', 'Data Science'] },
  { id: '5', name: 'Emily Rodriguez', username: 'emilyrodriguez', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&crop=face', reputation: 1920, skills: ['GraphQL', 'Node.js', 'APIs'] },
];

// Knowledge base categories
export const mockKnowledgeCategories = [
  { name: 'Backend Development', count: 234, icon: '⚙️' },
  { name: 'Frontend Development', count: 187, icon: '🎨' },
  { name: 'DevOps & Infrastructure', count: 156, icon: '🚀' },
  { name: 'Database Design', count: 143, icon: '🗄️' },
  { name: 'Architecture & Patterns', count: 198, icon: '🏗️' },
  { name: 'Security', count: 127, icon: '🔐' },
  { name: 'Performance Optimization', count: 112, icon: '⚡' },
  { name: 'Testing & QA', count: 89, icon: '✅' },
];

// Analytics data
export const mockAnalytics = {
  overview: {
    totalQuestions: 47,
    totalAnswers: 183,
    totalCodeReviews: 92,
    reputation: 4820,
    weeklyGrowth: 12.5,
  },
  contributions: [
    { month: 'Jan', questions: 8, answers: 22, reviews: 12 },
    { month: 'Feb', questions: 6, answers: 18, reviews: 9 },
    { month: 'Mar', questions: 12, answers: 28, reviews: 15 },
    { month: 'Apr', questions: 9, answers: 25, reviews: 11 },
    { month: 'May', questions: 7, answers: 20, reviews: 8 },
    { month: 'Jun', questions: 5, answers: 70, reviews: 37 },
  ],
};

// Live coding session data
export const mockLiveSession = {
  id: 'session-1',
  title: 'Interview with Stripe',
  interviewer: 'Sarah Kim',
  duration: '45 minutes',
  problem: 'Design a rate limiter for an API',
  language: 'typescript',
  code: `class RateLimiter {\n  constructor(maxRequests: number, windowMs: number) {\n    this.maxRequests = maxRequests;\n    this.windowMs = windowMs;\n    this.requests = new Map();\n  }\n\n  isAllowed(userId: string): boolean {\n    const now = Date.now();\n    const userRequests = this.requests.get(userId) || [];\n    const validRequests = userRequests.filter(t => now - t < this.windowMs);\n    \n    if (validRequests.length < this.maxRequests) {\n      validRequests.push(now);\n      this.requests.set(userId, validRequests);\n      return true;\n    }\n    return false;\n  }\n}`,
  status: 'in-progress',
  participants: [
    { name: 'Sarah Kim', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&crop=face' },
    { name: 'Alex Chen', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face' },
  ],
};
