import type { User, Question, CodeReview, Job, Article, Notification, LeaderboardEntry, AnalyticsData, TeamChannel } from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "1",
    name: "Alex Chen",
    email: "alex@example.com",
    username: "alexchen",
    avatar: "/assets/images/alex_chen.png",
    role: "developer",
    reputation: 4820,
    badges: [
      { id: "b1", name: "Code Wizard", description: "Solved 100+ problems", icon: "🧙", color: "#2563EB", earnedAt: "2024-01-15", rarity: "rare" },
      { id: "b2", name: "Top Contributor", description: "Top 1% contributor", icon: "⭐", color: "#F59E0B", earnedAt: "2024-03-10", rarity: "legendary" },
    ],
    skills: ["React", "TypeScript", "Node.js", "Python", "GraphQL", "Docker"],
    bio: "Full-stack developer passionate about scalable systems and open source.",
    location: "San Francisco, CA",
    website: "https://alexchen.dev",
    github: "alexchen",
    twitter: "alexchen_dev",
    joinedAt: "2023-02-10",
    isVerified: true,
    streak: 42,
    title: "Senior Full-Stack Developer",
    followers: 1240,
    following: 380,
    contributions: 892,
  },
  {
    id: "2",
    name: "Sarah Mitchell",
    email: "sarah@example.com",
    username: "sarahm",
    avatar: "/assets/images/sarah_mitchell.png",
    role: "expert",
    reputation: 12350,
    badges: [
      { id: "b3", name: "Expert Mentor", description: "Mentored 50+ developers", icon: "🎓", color: "#22C55E", earnedAt: "2024-02-20", rarity: "legendary" },
      { id: "b4", name: "Security Champion", description: "Found critical vulnerabilities", icon: "🛡️", color: "#EF4444", earnedAt: "2024-01-05", rarity: "epic" },
    ],
    skills: ["System Design", "Security", "Rust", "Go", "Kubernetes", "AWS"],
    bio: "Principal engineer & security researcher. Making the web safer one review at a time.",
    location: "Austin, TX",
    website: "https://sarahmitchell.io",
    github: "sarahm",
    twitter: "sarah_security",
    joinedAt: "2022-08-15",
    isVerified: true,
    streak: 128,
    title: "Principal Security Engineer",
    followers: 5840,
    following: 210,
    contributions: 3241,
  },
  {
    id: "3",
    name: "TechForge Inc.",
    email: "hiring@techforge.com",
    username: "techforge",
    avatar: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=200&h=200&fit=crop",
    role: "recruiter",
    reputation: 890,
    badges: [
      { id: "b5", name: "Top Employer", description: "Hired 20+ developers", icon: "🏢", color: "#8B5CF6", earnedAt: "2024-04-01", rarity: "rare" },
    ],
    skills: ["Hiring", "Technical Assessment", "Team Building"],
    bio: "Building the future of software at TechForge. We're always hiring great engineers.",
    location: "New York, NY",
    website: "https://techforge.com",
    github: "techforge",
    twitter: "techforgeinc",
    joinedAt: "2023-06-01",
    isVerified: true,
    streak: 15,
    company: "TechForge Inc.",
    title: "Head of Engineering Talent",
    followers: 2100,
    following: 450,
    contributions: 45,
  },
  {
    id: "4",
    name: "Admin User",
    email: "admin@stacktruth.com",
    username: "admin",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop",
    role: "admin",
    reputation: 99999,
    badges: [
      { id: "b6", name: "Platform Guardian", description: "Keeping StackTruth safe", icon: "⚡", color: "#F59E0B", earnedAt: "2023-01-01", rarity: "legendary" },
    ],
    skills: ["Platform Management", "Moderation", "Analytics"],
    bio: "StackTruth platform administrator.",
    location: "Remote",
    website: "https://stacktruth.com",
    github: "st-admin",
    twitter: "stacktruth",
    joinedAt: "2023-01-01",
    isVerified: true,
    streak: 365,
    title: "Platform Administrator",
    followers: 12400,
    following: 100,
    contributions: 5000,
  },
  {
    id: "5",
    name: "Jordan Rivera",
    email: "jordan@example.com",
    username: "jordanr",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
    role: "developer",
    reputation: 2340,
    badges: [
      { id: "b7", name: "Rising Star", description: "Fast reputation growth", icon: "🌟", color: "#F59E0B", earnedAt: "2024-05-01", rarity: "common" },
    ],
    skills: ["Vue.js", "Python", "FastAPI", "PostgreSQL", "Redis"],
    bio: "Backend developer building high-performance APIs and data pipelines.",
    location: "Toronto, Canada",
    website: "",
    github: "jordanr",
    twitter: "jordan_codes",
    joinedAt: "2024-01-20",
    isVerified: false,
    streak: 18,
    title: "Backend Engineer",
    followers: 340,
    following: 520,
    contributions: 234,
  },
  {
    id: "6",
    name: "Priya Sharma",
    email: "priya@example.com",
    username: "priyas",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    role: "expert",
    reputation: 8940,
    badges: [
      { id: "b8", name: "ML Pioneer", description: "Top ML contributor", icon: "🤖", color: "#22C55E", earnedAt: "2024-02-15", rarity: "epic" },
    ],
    skills: ["Python", "TensorFlow", "PyTorch", "MLOps", "Data Science", "LLMs"],
    bio: "ML Engineer specializing in large language models and production AI systems.",
    location: "Seattle, WA",
    website: "https://priyasharma.ai",
    github: "priyas",
    twitter: "priya_ml",
    joinedAt: "2022-11-10",
    isVerified: true,
    streak: 87,
    title: "Senior ML Engineer",
    followers: 3200,
    following: 180,
    contributions: 1892,
  },
];

export const MOCK_QUESTIONS: Question[] = [
  {
    id: "q1",
    title: "How to handle race conditions in React's useEffect with async operations?",
    body: "I'm building a search feature that fetches results from an API. When the user types quickly, I'm getting race conditions where older responses override newer ones...",
    author: MOCK_USERS[0],
    tags: ["React", "TypeScript", "async", "hooks"],
    votes: 142,
    answers: 8,
    views: 3420,
    createdAt: "2024-05-10T14:30:00Z",
    isAnswered: true,
    isFeatured: true,
    bounty: 50,
  },
  {
    id: "q2",
    title: "Optimizing PostgreSQL queries for time-series data with 100M+ rows",
    body: "We're storing IoT sensor data and performance is degrading significantly at scale. Using BRIN indexes but still seeing slow queries...",
    author: MOCK_USERS[4],
    tags: ["PostgreSQL", "performance", "indexing", "time-series"],
    votes: 89,
    answers: 5,
    views: 2180,
    createdAt: "2024-05-12T09:15:00Z",
    isAnswered: true,
    isFeatured: false,
    bounty: 100,
  },
  {
    id: "q3",
    title: "Rust async runtime - tokio vs async-std: which should I choose in 2025?",
    body: "Starting a new microservices project in Rust. I've been reading conflicting opinions about tokio vs async-std performance and ecosystem maturity...",
    author: MOCK_USERS[0],
    tags: ["Rust", "async", "tokio", "performance"],
    votes: 67,
    answers: 3,
    views: 1890,
    createdAt: "2024-05-13T16:45:00Z",
    isAnswered: false,
    isFeatured: true,
    bounty: 0,
  },
  {
    id: "q4",
    title: "Kubernetes pod autoscaling based on custom application metrics?",
    body: "I need to scale pods based on a custom metric from our application - specifically the number of pending jobs in a queue...",
    author: MOCK_USERS[4],
    tags: ["Kubernetes", "DevOps", "HPA", "metrics"],
    votes: 54,
    answers: 2,
    views: 1234,
    createdAt: "2024-05-14T11:20:00Z",
    isAnswered: false,
    isFeatured: false,
  },
  {
    id: "q5",
    title: "GraphQL vs REST for microservices inter-service communication?",
    body: "Our monolith is being broken into microservices. We're debating whether to use GraphQL or REST for service-to-service communication...",
    author: MOCK_USERS[0],
    tags: ["GraphQL", "REST", "microservices", "API"],
    votes: 201,
    answers: 12,
    views: 5640,
    createdAt: "2024-05-08T08:00:00Z",
    isAnswered: true,
    isFeatured: true,
    bounty: 200,
  },
  {
    id: "q6",
    title: "How to implement zero-downtime database migrations with 99.99% SLA?",
    body: "Our production database has 50M users and we need to add a new required column. How do we do this without any downtime?",
    author: MOCK_USERS[4],
    tags: ["Database", "DevOps", "PostgreSQL", "migration"],
    votes: 178,
    answers: 9,
    views: 4320,
    createdAt: "2024-05-09T13:00:00Z",
    isAnswered: true,
    isFeatured: false,
  },
  {
    id: "q7",
    title: "Understanding Memory Management in Go with Large Buffers",
    body: "I'm working with large byte buffers in Go and noticing that memory isn't being released back to the OS as quickly as I'd expect. How does the Go scavenger work?",
    author: MOCK_USERS[5],
    tags: ["Go", "Memory", "Performance", "Runtime"],
    votes: 45,
    answers: 4,
    views: 890,
    createdAt: "2024-05-15T10:00:00Z",
    isAnswered: true,
    isFeatured: false,
  },
  {
    id: "q8",
    title: "Docker image size optimization for large Python applications",
    body: "Our Python Docker images are over 1GB. We're using multi-stage builds but the base image is still heavy. Any tips for reducing size?",
    author: MOCK_USERS[0],
    tags: ["Docker", "Python", "DevOps", "Optimization"],
    votes: 32,
    answers: 6,
    views: 750,
    createdAt: "2024-05-15T14:30:00Z",
    isAnswered: false,
    isFeatured: false,
  },
  {
    id: "q9",
    title: "How to implement distributed locking with Redis in a Node.js cluster?",
    body: "We need to ensure that only one node in our cluster processes a specific task at a time. Is Redlock the best approach?",
    author: MOCK_USERS[1],
    tags: ["Redis", "Node.js", "Distributed Systems", "Locking"],
    votes: 156,
    answers: 10,
    views: 4500,
    createdAt: "2024-05-14T09:00:00Z",
    isAnswered: true,
    isFeatured: true,
    bounty: 150,
  },
  {
    id: "q10",
    title: "Best practices for handling large-scale WebSocket connections in 2025?",
    body: "We're building a real-time collaboration tool and expecting 100k+ concurrent WebSocket connections. Should we use Socket.io or raw WebSockets?",
    author: MOCK_USERS[4],
    tags: ["WebSockets", "Architecture", "Real-time", "Scalability"],
    votes: 78,
    answers: 5,
    views: 1800,
    createdAt: "2024-05-16T08:15:00Z",
    isAnswered: false,
    isFeatured: true,
  },
  {
    id: "q11",
    title: "CI/CD pipeline security - protecting secrets in GitHub Actions",
    body: "What are the latest best practices for managing secrets and OIDC in GitHub Actions to prevent accidental exposure?",
    author: MOCK_USERS[0],
    tags: ["Security", "CI/CD", "DevOps", "GitHub Actions"],
    votes: 24,
    answers: 2,
    views: 420,
    createdAt: "2024-05-16T11:45:00Z",
    isAnswered: true,
    isFeatured: false,
  },
  {
    id: "q12",
    title: "Performance comparison: Bun vs Node.js vs Deno in production",
    body: "I've seen many benchmarks, but what's the actual production experience when migrating from Node.js to Bun for high-traffic APIs?",
    author: MOCK_USERS[1],
    tags: ["Bun", "Node.js", "Deno", "Performance"],
    votes: 210,
    answers: 15,
    views: 8900,
    createdAt: "2024-05-16T15:00:00Z",
    isAnswered: true,
    isFeatured: true,
  },
];

export const MOCK_CODE_REVIEWS: CodeReview[] = [
  {
    id: "cr1",
    title: "Authentication middleware with JWT refresh token rotation",
    description: "Implementing secure JWT authentication with automatic token rotation. Looking for security review and performance suggestions.",
    author: MOCK_USERS[0],
    language: "typescript",
    code: `import jwt from 'jsonwebtoken';
import { Request, Response, NextFunction } from 'express';

const SECRET = process.env.JWT_SECRET!;

export async function authMiddleware(
  req: Request,
  res: Response,
  next: NextFunction
) {
  const token = req.headers.authorization?.split(' ')[1];
  
  if (!token) {
    return res.status(401).json({ error: 'No token provided' });
  }
  
  try {
    const decoded = jwt.verify(token, SECRET) as any;
    req.user = decoded;
    next();
  } catch (error) {
    return res.status(401).json({ error: 'Invalid token' });
  }
}`,
    score: 72,
    status: "reviewed",
    issues: [
      { id: "i1", type: "security", line: 3, message: "Hardcoded secret key reference without validation", suggestion: "Add validation that JWT_SECRET is set and meets minimum length requirements." },
      { id: "i2", type: "error", line: 14, message: "Using 'any' type defeats TypeScript safety", suggestion: "Define a proper decoded token interface: interface DecodedToken { userId: string; email: string; iat: number; exp: number; }" },
      { id: "i3", type: "warning", line: 20, message: "Generic error handling loses error context", suggestion: "Distinguish between TokenExpiredError and JsonWebTokenError for better client feedback." },
    ],
    suggestions: [
      "Implement refresh token rotation to prevent token theft",
      "Add rate limiting on the authentication endpoint",
      "Consider using RS256 instead of HS256 for microservices",
    ],
    reviewedBy: MOCK_USERS[1],
    createdAt: "2024-05-13T10:00:00Z",
    tags: ["security", "authentication", "JWT", "Node.js"],
  },
  {
    id: "cr2",
    title: "React custom hook for infinite scroll with intersection observer",
    description: "Performance-optimized infinite scroll implementation. Please review for memory leaks and edge cases.",
    author: MOCK_USERS[4],
    language: "typescript",
    code: `import { useState, useEffect, useRef, useCallback } from 'react';

export function useInfiniteScroll<T>(
  fetchFn: (page: number) => Promise<T[]>,
  options = { threshold: 0.5 }
) {
  const [data, setData] = useState<T[]>([]);
  const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(false);
  const [hasMore, setHasMore] = useState(true);
  const observerRef = useRef<IntersectionObserver | null>(null);

  const loadMore = useCallback(async () => {
    if (loading || !hasMore) return;
    setLoading(true);
    const result = await fetchFn(page);
    if (result.length === 0) {
      setHasMore(false);
    } else {
      setData(prev => [...prev, ...result]);
      setPage(prev => prev + 1);
    }
    setLoading(false);
  }, [page, loading, hasMore, fetchFn]);

  return { data, loading, hasMore, loadMore, observerRef };
}`,
    score: 85,
    status: "approved",
    issues: [
      { id: "i4", type: "warning", line: 16, message: "Missing error handling in async operation", suggestion: "Wrap fetchFn call in try-catch to handle network failures gracefully." },
      { id: "i5", type: "info", line: 11, message: "IntersectionObserver cleanup not implemented", suggestion: "Return cleanup function to disconnect observer when component unmounts." },
    ],
    suggestions: [
      "Add error state for failed requests",
      "Implement retry logic with exponential backoff",
      "Consider debouncing the load trigger",
    ],
    reviewedBy: MOCK_USERS[1],
    createdAt: "2024-05-12T15:30:00Z",
    tags: ["React", "performance", "hooks", "TypeScript"],
  },
];

export const MOCK_JOBS: Job[] = [
  {
    id: "j1",
    title: "Senior Full-Stack Engineer",
    company: "Vercel",
    companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=Vercel",
    location: "Remote (US)",
    type: "full-time",
    salary: "$180k - $240k",
    description: "Join the team building the future of web deployment infrastructure. Work on high-impact products used by millions of developers.",
    requirements: ["5+ years experience", "Next.js expertise", "System design skills", "Open source contributions"],
    skills: ["Next.js", "TypeScript", "Go", "PostgreSQL", "Redis"],
    postedAt: "2024-05-10T00:00:00Z",
    deadline: "2024-06-10T00:00:00Z",
    applicants: 284,
    isRemote: true,
    isFeatured: true,
    experienceLevel: "senior",
    recruiter: MOCK_USERS[2],
  },
  {
    id: "j2",
    title: "Staff Machine Learning Engineer",
    company: "Anthropic",
    companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=Anthropic",
    location: "San Francisco, CA",
    type: "full-time",
    salary: "$250k - $350k",
    description: "Help build safe and beneficial AI systems. Work directly on frontier model training, alignment research, and deployment infrastructure.",
    requirements: ["PhD or 7+ years ML", "Deep learning expertise", "Research background", "Python mastery"],
    skills: ["Python", "PyTorch", "CUDA", "Distributed Systems", "MLOps"],
    postedAt: "2024-05-08T00:00:00Z",
    deadline: "2024-06-15T00:00:00Z",
    applicants: 1024,
    isRemote: false,
    isFeatured: true,
    experienceLevel: "lead",
    recruiter: MOCK_USERS[2],
  },
  {
    id: "j3",
    title: "Backend Engineer - Platform Infrastructure",
    company: "Linear",
    companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=Linear",
    location: "Remote (Global)",
    type: "full-time",
    salary: "$140k - $200k",
    description: "Build the infrastructure powering the world's best issue tracking tool. Focus on performance, reliability, and developer experience.",
    requirements: ["3+ years backend", "Distributed systems knowledge", "PostgreSQL experience"],
    skills: ["Node.js", "TypeScript", "PostgreSQL", "Redis", "Kubernetes"],
    postedAt: "2024-05-12T00:00:00Z",
    deadline: "2024-06-12T00:00:00Z",
    applicants: 156,
    isRemote: true,
    isFeatured: false,
    experienceLevel: "mid",
    recruiter: MOCK_USERS[2],
  },
  {
    id: "j4",
    title: "Frontend Developer - React Specialist",
    company: "Figma",
    companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=Figma",
    location: "Remote (US/EU)",
    type: "contract",
    salary: "$120/hr",
    description: "Build premium UI components and design system infrastructure for Figma's web platform.",
    requirements: ["4+ years React", "Design systems experience", "Performance optimization"],
    skills: ["React", "TypeScript", "WebGL", "CSS", "Figma"],
    postedAt: "2024-05-14T00:00:00Z",
    deadline: "2024-05-28T00:00:00Z",
    applicants: 89,
    isRemote: true,
    isFeatured: false,
    experienceLevel: "senior",
    recruiter: MOCK_USERS[2],
  },
  {
    id: "j5",
    title: "DevOps / Platform Engineer",
    company: "GitHub",
    companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=GitHub",
    location: "Remote (Global)",
    type: "full-time",
    salary: "$160k - $220k",
    description: "Scale GitHub Actions infrastructure to handle billions of CI/CD runs daily. Own platform reliability and performance.",
    requirements: ["5+ years DevOps", "Kubernetes at scale", "SRE experience"],
    skills: ["Kubernetes", "Go", "Terraform", "AWS", "Prometheus"],
    postedAt: "2024-05-11T00:00:00Z",
    deadline: "2024-06-11T00:00:00Z",
    applicants: 412,
    isRemote: true,
    isFeatured: true,
    experienceLevel: "senior",
    recruiter: MOCK_USERS[2],
  },
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: "a1",
    title: "Building Type-Safe APIs with tRPC and Next.js 14",
    excerpt: "A comprehensive guide to building end-to-end type-safe APIs that eliminate the runtime type mismatch bugs that plague REST APIs.",
    content: "",
    author: MOCK_USERS[1],
    tags: ["TypeScript", "tRPC", "Next.js", "API"],
    category: "Tutorial",
    readTime: 12,
    likes: 842,
    views: 15420,
    comments: 64,
    publishedAt: "2024-05-10T00:00:00Z",
    isFeatured: true,
    coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=400&fit=crop",
  },
  {
    id: "a2",
    title: "Advanced Rust Patterns for Systems Programming",
    excerpt: "Deep dive into zero-cost abstractions, lifetime management, and async patterns that make Rust the ideal systems programming language.",
    content: "",
    author: MOCK_USERS[1],
    tags: ["Rust", "Systems Programming", "Performance"],
    category: "Deep Dive",
    readTime: 20,
    likes: 1240,
    views: 28900,
    comments: 92,
    publishedAt: "2024-05-08T00:00:00Z",
    isFeatured: true,
    coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=400&fit=crop&q=80&sat=-30",
  },
  {
    id: "a3",
    title: "Designing Resilient Microservices with Circuit Breakers",
    excerpt: "Learn how to implement the circuit breaker pattern to build fault-tolerant distributed systems that degrade gracefully.",
    content: "",
    author: MOCK_USERS[5],
    tags: ["Microservices", "System Design", "Resilience", "Patterns"],
    category: "Architecture",
    readTime: 15,
    likes: 634,
    views: 11200,
    comments: 38,
    publishedAt: "2024-05-12T00:00:00Z",
    isFeatured: false,
    coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=400&fit=crop",
  },
  {
    id: "a4",
    title: "LLM Fine-tuning on Custom Datasets: A Production Guide",
    excerpt: "From data preparation to deployment, everything you need to know to fine-tune and serve your own language models at scale.",
    content: "",
    author: MOCK_USERS[5],
    tags: ["AI", "LLMs", "Python", "MLOps"],
    category: "AI/ML",
    readTime: 25,
    likes: 2140,
    views: 48500,
    comments: 187,
    publishedAt: "2024-05-09T00:00:00Z",
    isFeatured: true,
    coverImage: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&h=400&fit=crop",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: "n1", type: "answer", title: "New answer on your question", message: "Sarah Mitchell answered your question about React race conditions", isRead: false, createdAt: "2024-05-14T10:30:00Z", link: "/questions/q1", actor: MOCK_USERS[1] },
  { id: "n2", type: "vote", title: "Your answer was upvoted", message: "Your answer received 15 upvotes in the last hour", isRead: false, createdAt: "2024-05-14T09:00:00Z" },
  { id: "n3", type: "badge", title: "New badge earned!", message: "You earned the 'Code Wizard' badge for solving 100 problems", isRead: false, createdAt: "2024-05-13T18:00:00Z" },
  { id: "n4", type: "mention", title: "You were mentioned", message: "Jordan Rivera mentioned you in a discussion about async patterns", isRead: true, createdAt: "2024-05-13T14:00:00Z", actor: MOCK_USERS[4] },
  { id: "n5", type: "review", title: "Code review completed", message: "Sarah Mitchell reviewed your JWT authentication code", isRead: true, createdAt: "2024-05-13T11:00:00Z", actor: MOCK_USERS[1] },
  { id: "n6", type: "follow", title: "New follower", message: "Priya Sharma started following you", isRead: true, createdAt: "2024-05-12T16:30:00Z", actor: MOCK_USERS[5] },
  { id: "n7", type: "job", title: "Job match found", message: "Vercel posted a role matching your React skills", isRead: true, createdAt: "2024-05-12T09:00:00Z" },
  { id: "n8", type: "system", title: "StackTruth v2.0 launched", message: "Check out the new AI code review features and live coding rooms", isRead: true, createdAt: "2024-05-11T12:00:00Z" },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, user: MOCK_USERS[1], score: 12350, change: 2, answers: 420, questions: 38, codeReviews: 156 },
  { rank: 2, user: MOCK_USERS[5], score: 8940, change: -1, answers: 312, questions: 67, codeReviews: 89 },
  { rank: 3, user: MOCK_USERS[0], score: 4820, change: 1, answers: 198, questions: 124, codeReviews: 45 },
  { rank: 4, user: MOCK_USERS[4], score: 2340, change: 3, answers: 87, questions: 56, codeReviews: 12 },
  { rank: 5, user: { ...MOCK_USERS[0], id: "u5", name: "Marcus Johnson", username: "marcusj", reputation: 1840, avatar: "" }, score: 1840, change: -2, answers: 65, questions: 34, codeReviews: 8 },
  { rank: 6, user: { ...MOCK_USERS[4], id: "u6", name: "Emily Zhang", username: "emilyzhang", reputation: 1590, avatar: "" }, score: 1590, change: 5, answers: 58, questions: 28, codeReviews: 15 },
  { rank: 7, user: { ...MOCK_USERS[0], id: "u7", name: "David Kim", username: "davidkim", reputation: 1320, avatar: "" }, score: 1320, change: 0, answers: 45, questions: 22, codeReviews: 6 },
  { rank: 8, user: { ...MOCK_USERS[4], id: "u8", name: "Aisha Patel", username: "aishap", reputation: 1180, avatar: "" }, score: 1180, change: 4, answers: 38, questions: 18, codeReviews: 10 },
];

export const MOCK_ANALYTICS: AnalyticsData = {
  contributions: Array.from({ length: 52 }, (_, week) =>
    Array.from({ length: 7 }, (_, day) => ({
      date: new Date(2024, 0, week * 7 + day + 1).toISOString().split("T")[0],
      count: Math.random() > 0.3 ? Math.floor(Math.random() * 8) : 0,
    }))
  ).flat(),
  skillGrowth: [
    { skill: "React", level: 92, growth: 5 },
    { skill: "TypeScript", level: 88, growth: 8 },
    { skill: "Node.js", level: 80, growth: 3 },
    { skill: "Python", level: 74, growth: 12 },
    { skill: "Docker", level: 68, growth: 15 },
    { skill: "GraphQL", level: 72, growth: 7 },
  ],
  engagement: [
    { week: "Week 1", views: 1240, votes: 48, answers: 12 },
    { week: "Week 2", views: 1850, votes: 67, answers: 18 },
    { week: "Week 3", views: 1420, votes: 52, answers: 14 },
    { week: "Week 4", views: 2340, votes: 89, answers: 24 },
    { week: "Week 5", views: 1980, votes: 74, answers: 20 },
    { week: "Week 6", views: 2890, votes: 112, answers: 31 },
    { week: "Week 7", views: 3240, votes: 128, answers: 38 },
    { week: "Week 8", views: 2760, votes: 98, answers: 28 },
  ],
  topTags: [
    { tag: "React", count: 124, color: "#61DAFB" },
    { tag: "TypeScript", count: 98, color: "#3178C6" },
    { tag: "Node.js", count: 76, color: "#68A063" },
    { tag: "Python", count: 64, color: "#F7CB3F" },
    { tag: "Docker", count: 45, color: "#2496ED" },
  ],
};

export const TECH_TAGS = [
  "React", "Vue", "Angular", "TypeScript", "JavaScript", "Python", "Rust", "Go",
  "Node.js", "GraphQL", "REST", "PostgreSQL", "MongoDB", "Redis", "Docker",
  "Kubernetes", "AWS", "GCP", "Azure", "Terraform", "CI/CD", "DevOps",
  "Machine Learning", "LLMs", "System Design", "Security", "Performance",
];

export const MOCK_TEAM_CHANNELS: TeamChannel[] = [
  {
    id: "tc1",
    name: "general",
    description: "General team discussion",
    members: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[4]],
    isPrivate: false,
    createdAt: "2024-01-01",
    messages: [
      { id: "m1", author: MOCK_USERS[1], content: "Just reviewed the new auth implementation. Great work everyone!", type: "text", createdAt: "2024-05-14T10:00:00Z", reactions: { "👍": 3, "🚀": 2 } },
      { id: "m2", author: MOCK_USERS[0], content: "Thanks! Working on fixing the token rotation issue now.", type: "text", createdAt: "2024-05-14T10:05:00Z", reactions: { "💪": 1 } },
      { id: "m3", author: MOCK_USERS[4], content: "Here's the updated API schema:", type: "code", createdAt: "2024-05-14T10:10:00Z", reactions: {} },
    ],
  },
  {
    id: "tc2",
    name: "code-reviews",
    description: "Code review requests and discussions",
    members: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[5]],
    isPrivate: false,
    createdAt: "2024-01-01",
    messages: [
      { id: "m4", author: MOCK_USERS[1], content: "New review ready for the database query optimizer PR", type: "text", createdAt: "2024-05-14T09:00:00Z", reactions: { "👀": 4 } },
      { id: "m5", author: MOCK_USERS[5], content: "I'll take a look at the ML pipeline changes too", type: "text", createdAt: "2024-05-14T09:15:00Z", reactions: {} },
    ],
  },
];

export const PRICING_PLANS = [
  {
    id: "free",
    name: "Developer",
    price: 0,
    period: "forever",
    description: "Perfect for individual developers getting started",
    features: [
      "Unlimited Q&A participation",
      "5 code reviews per month",
      "Basic AI assistant (50 queries/mo)",
      "Community forums access",
      "Public profile & portfolio",
      "Job board access",
    ],
    limitations: ["No private workspaces", "Limited analytics", "Standard support"],
    cta: "Get Started Free",
    isPopular: false,
    color: "from-slate-600 to-slate-700",
  },
  {
    id: "pro",
    name: "Pro Developer",
    price: 19,
    period: "month",
    description: "For serious developers building their reputation",
    features: [
      "Everything in Developer",
      "Unlimited code reviews",
      "Advanced AI assistant (500 queries/mo)",
      "Private team workspace (5 members)",
      "Advanced analytics dashboard",
      "Live coding sessions",
      "Priority code review queue",
      "Expert mentorship access",
    ],
    limitations: [],
    cta: "Start Pro Trial",
    isPopular: true,
    color: "from-blue-600 to-blue-700",
  },
  {
    id: "team",
    name: "Team",
    price: 79,
    period: "month",
    description: "For engineering teams and growing companies",
    features: [
      "Everything in Pro",
      "Unlimited team members",
      "Unlimited AI assistant queries",
      "Custom knowledge base",
      "Advanced code review engine",
      "Team analytics & insights",
      "Priority support",
      "Custom integrations",
      "Admin controls & audit logs",
    ],
    limitations: [],
    cta: "Start Team Trial",
    isPopular: false,
    color: "from-purple-600 to-purple-700",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 299,
    period: "month",
    description: "For large organizations with advanced needs",
    features: [
      "Everything in Team",
      "Dedicated workspace",
      "Custom AI model fine-tuning",
      "SSO & advanced security",
      "SLA guarantee (99.9%)",
      "Dedicated account manager",
      "On-premise deployment option",
      "Custom badge & gamification",
      "Advanced compliance tools",
    ],
    limitations: [],
    cta: "Contact Sales",
    isPopular: false,
    color: "from-amber-600 to-orange-600",
  },
];

export const FAQS = [
  { question: "How does the reputation system work?", answer: "You earn reputation points by asking quality questions (+5), providing accepted answers (+15), receiving upvotes (+10), and completing code reviews (+20). Reputation unlocks platform features and expert status." },
  { question: "What makes StackTruth different from Stack Overflow?", answer: "StackTruth combines Q&A with AI-powered code review, live coding sessions, team workspaces, job matching, and a gamified reputation system — all in one premium developer platform." },
  { question: "Is the AI code review actually useful?", answer: "Our AI engine analyzes code for security vulnerabilities, performance issues, style violations, and best practice adherence. It's trained on millions of code reviews and continuously improved by expert contributors." },
  { question: "Can I use StackTruth for my team?", answer: "Yes! Team workspaces let you create private channels, shared code snippets, collaborative documentation, and team-specific knowledge bases with access controls." },
  { question: "How does expert verification work?", answer: "Experts are verified through a combination of reputation score (8,000+), contribution quality metrics, peer endorsements, and a manual review process by our expert panel." },
  { question: "Is there a free tier?", answer: "Yes, the Developer plan is free forever with generous limits. You get unlimited Q&A, 5 code reviews/month, and 50 AI queries. Upgrade for more power." },
];

export const TESTIMONIALS = [
  { name: "Linus Torvalds Jr.", role: "Staff Engineer, Netflix", avatar: "", text: "StackTruth's AI code review caught a critical security vulnerability I'd missed. The platform quality is outstanding — it's become essential to my daily workflow.", rating: 5 },
  { name: "Ada Rodriguez", role: "Principal ML Engineer, OpenAI", avatar: "", text: "The expert community here is phenomenal. I've gotten better answers in 20 minutes than from hours of documentation hunting. The reputation system ensures quality.", rating: 5 },
  { name: "Tony Chen", role: "CTO, YC Startup", avatar: "", text: "We use StackTruth's team workspace for all technical discussions. The collaborative code review and live coding features have cut our code review time in half.", rating: 5 },
  { name: "Mia Kovacs", role: "DevOps Lead, Stripe", avatar: "", text: "As a recruiter, finding developers through their StackTruth profiles and reputation scores is 10x more effective than traditional hiring. We've hired 8 engineers through the platform.", rating: 5 },
];
